[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
bonding_curve = "8FydojysL5DJ8M3s15JLFEbsKzyQ1BcFgSMVDvJetEEq"

[programs.localnet]
bonding_curve = "8FydojysL5DJ8M3s15JLFEbsKzyQ1BcFgSMVDvJetEEq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/wotori/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
setup = "avm use 0.29.0 && agave-install init 1.18.26 && rustup default stable"
build = "anchor build && cp target/idl/*.json ./idl/ && cp target/types/*.ts ./idl/"